using XReports.SchemaBuilders.ReportCellProviders.ValueProviders;
using XReports.Table;

namespace XReports.SchemaBuilders.ReportCellProviders
{
    /// <summary>
    /// Provider of cells which value is generated by value provider.
    /// </summary>
    /// <typeparam name="TSourceItem">Type of data source item.</typeparam>
    /// <typeparam name="TValue">Type of cell value.</typeparam>
    public class ValueProviderReportCellProvider<TSourceItem, TValue> : ReportCellProvider<TSourceItem, TValue>
    {
        private readonly IValueProvider<TValue> provider;

        /// <summary>
        /// Initializes a new instance of the <see cref="ValueProviderReportCellProvider{TSourceItem, TValue}"/> class.
        /// </summary>
        /// <param name="provider">Provider to use for generating cells values.</param>
        public ValueProviderReportCellProvider(IValueProvider<TValue> provider)
        {
            this.provider = provider;
        }

        /// <inheritdoc/>
        public override ReportCell GetCell(TSourceItem item)
        {
            return this.GetCell(this.provider.GetValue());
        }
    }
}
